services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    volumes:
      - ./config.json:/app/config.json
      - ./servers/:/app/servers/
      - ./templates/:/app/templates/
